// packages/pinelab-storefront-client/src/ministore/CustomerDetails.vue
<template>
  <form v-on:submit.prevent="submit()">
    <h1>Jouw gegevens</h1>
    <div class="grid-x grid-padding-x">
      <div class="cell small-6">
        <label
          >Bedrijfsnaam
          <input type="text" name="company" v-model="address.company" />
        </label>
      </div>
    </div>
    <div class="grid-x grid-padding-x">
      <div class="cell small-6">
        <label
          >Voornaam*
          <input
            type="text"
            name="firstname"
            required
            v-model="customer.firstName"
          />
        </label>
      </div>
      <div class="cell small-6">
        <label
          >Achternaam*
          <input
            type="text"
            name="lastname"
            required
            v-model="customer.lastName"
          />
        </label>
      </div>
    </div>
    <div class="grid-x grid-padding-x">
      <div class="cell small-6">
        <label
          >Telefoonnummer
          <input type="tel" name="phoneNumber" v-model="customer.phoneNumber" />
        </label>
      </div>
      <div class="cell small-6">
        <label
          >Email*
          <input
            type="email"
            name="email"
            required
            v-model="customer.emailAddress"
          />
        </label>
      </div>
    </div>
    <div class="grid-x grid-padding-x">
      <div class="cell small-8">
        <label
          >Straat*
          <input
            type="text"
            name="street"
            required
            v-model="address.streetLine1"
          />
        </label>
      </div>
      <div class="cell small-4">
        <label
          >Huisnr*
          <input
            type="text"
            name="housenr"
            required
            v-model="address.streetLine2"
          />
        </label>
      </div>
    </div>
    <div class="grid-x grid-padding-x">
      <div class="cell small-8">
        <label
          >Plaats*
          <input type="text" name="city" required v-model="address.city" />
        </label>
      </div>
      <div class="cell small-4">
        <label
          >Postcode*
          <input
            type="text"
            name="postalcode"
            required
            v-model="address.postalCode"
          />
        </label>
      </div>
    </div>
    <div class="grid-x grid-padding-x">
      <div class="cell small-6">
        <label
          >Land
          <select name="country" v-model="address.countryCode">
            <option value="nl" selected>Nederland</option>
            <option value="de">Duitsland</option>
            <option value="be">België</option>
          </select>
        </label>
      </div>
    </div>
    <div class="grid-x grid-padding-x">
      <div class="cell small-12 text-right">
        <input type="submit" class="button" value="BESTEL" />
      </div>
    </div>
  </form>
</template>
<script>
export default {
  mixins: [require('./empty-basket-validator')],
  data() {
    return {
      customer: {
        emailAddress: undefined,
        firstName: undefined,
        lastName: undefined,
        phoneNumber: undefined,
      },
      address: {
        company: undefined,
        city: undefined,
        streetLine1: undefined,
        streetLine2: undefined,
        postalCode: undefined,
        countryCode: 'nl',
      },
    };
  },
  methods: {
    async submit() {
      const address = {
        ...this.address,
        fullName: `${this.customer.firstName} ${this.customer.lastName}`,
        defaultBillingAddress: true,
        defaultShippingAddress: true,
        phoneNumber: this.customer.phoneNumber,
      };
      await this.$vendure.setCustomerForOrder(this.customer);
      await this.$vendure.setOrderShippingAddress(address);
      this.$router.push('/shipping/');
    },
    getCountryCode(country) {
      switch (country) {
        case 'Nederland':
          return 'nl';
        case 'België':
          return 'be';
        case 'Duitsland':
          return 'de';
        default:
          return 'nl';
      }
    },
  },
  async mounted() {
    const activeOrder = await this.$vendure.getActiveOrder();
    // Set Customer, if already set on order
    this.customer.firstName = activeOrder?.customer?.firstName;
    this.customer.lastName = activeOrder?.customer?.lastName;
    this.customer.phoneNumber = activeOrder?.customer?.phoneNumber;
    this.customer.emailAddress = activeOrder?.customer?.emailAddress;
    // Set Address, if already set on order
    this.address.company = activeOrder?.shippingAddress?.company;
    this.address.streetLine1 = activeOrder?.shippingAddress?.streetLine1;
    this.address.streetLine2 = activeOrder?.shippingAddress?.streetLine2;
    this.address.city = activeOrder?.shippingAddress?.city;
    this.address.postalCode = activeOrder?.shippingAddress?.postalCode;
    if (activeOrder?.shippingAddress?.country) {
      this.address.countryCode = this.getCountryCode(
        activeOrder?.shippingAddress?.country
      );
    }
  },
};
</script>

// storefront/src/app/customer-details/customer-details.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {CreateAddressInput, CreateCustomerInput} from '../../generated/graphql';
import {VendureService} from '../vendure/vendure.service';
import {Router} from '@angular/router';

@Component({
  selector: 'app-customer-details',
  templateUrl: './customer-details.component.html',
  styleUrls: ['./customer-details.component.scss']
})
export class CustomerDetailsComponent implements OnInit {

  constructor(private vendureService: VendureService, private router: Router) { }

  async submit(event): Promise<void> {
    event.preventDefault();
    const customer: CreateCustomerInput = {
      emailAddress: event.target.email.value,
      firstName: event.target.firstname.value,
      lastName: event.target.lastname.value,
      phoneNumber: event.target.phonenumber.value,
    };
    const address: CreateAddressInput = {
      company: event.target.company.value,
      fullName: `${customer.firstName} ${customer.lastName}`,
      defaultBillingAddress: true,
      defaultShippingAddress: true,
      city: event.target.city.value,
      phoneNumber: customer.phoneNumber,
      countryCode: event.target.country.value,
      streetLine1: event.target.street.value,
      streetLine2: event.target.housenr.value,
      postalCode: event.target.postalcode.value,
    };
    await this.vendureService.setCustomerForOrder(customer);
    await this.vendureService.setOrderShippingAddress(address);
    await this.router.navigateByUrl('shipping');
  }

  ngOnInit(): void {
  }

}

<form (submit)="submit($event)" #customerDetailsForm>
  <h1 style="margin-bottom: 20px;"> Jouw gegevens</h1>
  <div class="grid-x grid-padding-x">
    <div class="cell small-6 ">
      <label>Bedrijfsnaam
        <input type="text" name="company">
      </label>
    </div>
  </div>
  <div class="grid-x grid-padding-x">
    <div class="cell small-6 ">
      <label>Voornaam*
        <input type="text" name="firstname" required>
      </label>
    </div>
    <div class="cell small-6">
      <label>Achternaam*
        <input type="text" name="lastname" required>
      </label>
    </div>
  </div>
  <div class="grid-x grid-padding-x">
    <div class="cell small-6 ">
      <label>Telefoonnummer
        <input type="tel" name="phonenumber">
      </label>
    </div>
    <div class="cell small-6">
      <label>Email*
        <input type="email" name="email" required>
      </label>
    </div>
  </div>
  <div class="grid-x grid-padding-x">
    <div class="cell small-8">
      <label>Straat*
        <input type="text" name="street" required>
      </label>
    </div>
    <div class="cell small-4">
      <label>Huisnr*
        <input type="text" name="housenr" required>
      </label>
    </div>
  </div>
  <div class="grid-x grid-padding-x">
    <div class="cell small-8">
      <label>Plaats*
        <input type="text" name="city" required>
      </label>
    </div>
    <div class="cell small-4">
      <label>Postcode*
        <input type="text" name="postalcode" required>
      </label>
    </div>
  </div>
  <div class="grid-x grid-padding-x">
    <div class="cell small-6">
      <label>Land
        <select name="country">
          <option value="NL">Nederland</option>
          <option value="DE">Duitsland</option>
          <option value="BE">België</option>
        </select>
      </label>
    </div>
  </div>
  <div class="grid-x grid-padding-x">
    <div class="cell small-12 text-right">
      <input type="submit" class="button" value="Bestel">
    </div>
  </div>
</form>
