// _shared-components/src/components/AsyncImage.vue
<template>
  <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk8AEAAFIATgDK/mEAAAAASUVORK5CYII="
      ref="img" :alt="alt"/>
</template>

<script>
export default {
  props: ['src', 'alt'],
  watch: {
    src: function () {
      this.load();
    }
  },
  methods: {
    load() {
      // If not ready or already loaded
      if (!this.src || !this.$refs?.img?.src || this.$refs.img.src === this.src) {
        return;
      }
      this.$refs.img.src = this.src;
    }
  },
  async mounted() {
    // this.load();
  }
}
</script>

// storefront/src/app/async-image/async-image.component.ts
import {Component, ElementRef, Input, OnChanges, ViewChild} from '@angular/core';

/**
 * Shows a base64 placeholder first and the loads actual image async
 */
@Component({
  selector: 'app-async-image',
  templateUrl: './async-image.component.html'
})
export class AsyncImageComponent implements OnChanges{

  @Input()
  src: string;
  @Input()
  alt?: string;
  @ViewChild('img') img: ElementRef;

  ngOnChanges(): void {
    this.load();
  }

  load(): void {
    // If not ready or already loaded
    if (!this.src || !this.img || this.img.nativeElement.loaded) {
      return;
    }
    this.img.nativeElement.src = this.src;
    this.img.nativeElement.loaded = true;
  }

}

<img #img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk8AEAAFIATgDK/mEAAAAASUVORK5CYII="
     style="width: 100%;"
     (load)="load()" alt="{{ alt }}">
