// storefront/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import {VendureService} from '../vendure/vendure.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss']
})
export class CartComponent implements OnInit {

  constructor(private vendureService: VendureService) {
  }

  ngOnInit(): void {
  }

}

<div *ngIf="order?.lines?.length > 0;">
  <div class="grid-x small-up-2 medium-up-2 large-up-2 grid-padding-x text-right small-font">
    <div class="cell">
      <p>Totaal: </p>
    </div>
    <div class="cell">
      <strong> {{ order?.totalWithTax | euro }}</strong>
    </div>
  </div>

  <div *ngFor="let line of order?.lines; let i = index" class="grid-x small-font {{ (i % 2 === 0) ? 'accent-row' : ''}}"
       style="padding: 10px;">
    <div class="cell small-4 medium-3 large-2">
      <div class="product-thumbnail">
        <img src="{{ line.productVariant?.featuredAsset?.preview || line.featuredAsset?.preview }}" alt="{{ line.productVariant?.name }}">
      </div>
    </div>
    <div class="cell small-8 medium-9 large-10 text-right cart-details">
      <p class="cart-name">{{ line.productVariant?.product?.name }} </p>
      <span *ngIf="line.productVariant?.name !== line.productVariant?.product?.name"> {{ line.productVariant?.name }}&nbsp;</span>
      <span class="cart-price">{{ line.productVariant?.priceWithTax | euro}}</span>
      <app-number-input [value]="line.quantity" (numberChange)="updateQuantity(line.id, $event)"></app-number-input>
    </div>
  </div>

  <div class="grid-x small-up-2 medium-up-2 large-up-2 grid-padding-x text-right small-font" style="padding-top: 40px;">
    <div class="cell">
      <p>Subtotaal: </p>
    </div>
    <div class="cell">
      <p> {{ order?.subTotalWithTax | euro: 'leaveZeros' }}</p>
    </div>
    <div class="cell">
      <p>Verzendkosten: </p>
    </div>
    <div class="cell">
      <p> {{ order?.shippingWithTax | euro: 'leaveZeros' }}</p>
    </div>
    <div class="cell">
      <p>Totaal: </p>
    </div>
    <div class="cell">
      <strong> {{ order?.totalWithTax | euro: 'leaveZeros' }}</strong>
    </div>
    <div class="cell"></div>
    <div class="cell">
      <a class="button" routerLink="/customer-details">
        BESTEL
      </a>
    </div>
  </div>
</div>
<div *ngIf="!loading && !order?.lines?.length">
  <div class="grid-x small-up-1grid-padding-x text-center small-font">
    <div class="cell">
      <p>Je hebt nog niks in je winkelmand...</p>
      <img src="https://storage.googleapis.com/pinelab-shops-assets/angular-assets/mand.jpg" alt="Korter">
    </div>
  </div>
</div>

// _shared-components/src/components/Cart.vue
<template>
  <div>
    <div v-if="orderLines > 0">
      <div class="grid-x small-up-2 medium-up-2 large-up-2 grid-padding-x text-right small-font">
        <div class="cell">
          <p>Totaal: </p>
        </div>
        <div class="cell">
          <strong> {{ $store.activeOrder.totalWithTax | euro }}</strong>
        </div>
      </div>
      <!--
          <div *ngFor="let line of order?.lines; let i = index" class="grid-x small-font {{ (i % 2 === 0) ? 'accent-row' : ''}}"
               style="padding: 10px;">
            <div class="cell small-4 medium-3 large-2">
              <div class="product-thumbnail">
                <img src="{{ line.productVariant?.featuredAsset?.preview || line.featuredAsset?.preview }}" alt="{{ line.productVariant?.name }}">
              </div>
            </div>
            <div class="cell small-8 medium-9 large-10 text-right cart-details">
              <p class="cart-name">{{ line.productVariant?.product?.name }} </p>
              <span *ngIf="line.productVariant?.name !== line.productVariant?.product?.name"> {{ line.productVariant?.name }}&nbsp;</span>
              <span class="cart-price">{{ line.productVariant?.priceWithTax | euro}}</span>
              <app-number-input [value]="line.quantity" (numberChange)="updateQuantity(line.id, $event)"></app-number-input>
            </div>
          </div>

          <div class="grid-x small-up-2 medium-up-2 large-up-2 grid-padding-x text-right small-font" style="padding-top: 40px;">
            <div class="cell">
              <p>Subtotaal: </p>
            </div>
            <div class="cell">
              <p> {{ order?.subTotalWithTax | euro: 'leaveZeros' }}</p>
            </div>
            <div class="cell">
              <p>Verzendkosten: </p>
            </div>
            <div class="cell">
              <p> {{ order?.shippingWithTax | euro: 'leaveZeros' }}</p>
            </div>
            <div class="cell">
              <p>Totaal: </p>
            </div>
            <div class="cell">
              <strong> {{ order?.totalWithTax | euro: 'leaveZeros' }}</strong>
            </div>
            <div class="cell"></div>
            <div class="cell">
              <a class="button" routerLink="/customer-details">
                BESTEL
              </a>
            </div>
          </div>
        -->
    </div>
    <div v-if="!loading && !orderLines">
      <div class="grid-x small-up-1grid-padding-x text-center small-font">
        <div class="cell">
          <p>Je hebt nog niks in je winkelmand...</p>
          <img src="https://storage.googleapis.com/pinelab-shops-assets/angular-assets/mand.jpg" alt="Korter">
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      loading: true
    }
  },
  computed: {
    orderLines() {
      return this.$store.activeOrder?.lines?.length
    }

  }
}
</script>
